### ISSUE TITLE
Remove "Hons" from course names

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#44] opened 2013-08-20 14:52 UTC
Hi @etsupport @learningtechnology,

I'm really sorry, but I think we need to remove "(Hons)" from all the course names. I think I may have suggested including the "Hons" at some point, however I think it is totally unnecessary in the interface and adds clutter/visual noise making things difficult to read.

What do others think? Is there really a problem here?

If somebody could pick this up that would be great.

Cheers.

**Comment by ghost** [comment] 2013-08-20 14:54
UPDATE: the problem isn't so bad with courses that have their own space in LS. Problem is with courses that share spaces.

**Comment by themarkness** [comment] 2013-08-22 08:54
This is a duplicate of #43

**Closed as completed by themarkness** 2013-08-22 08:54 UTC
Labels: Duplicate
