### ISSUE TITLE
Back and forth arrows in StudentSMS not working

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#225] opened 2013-10-18 14:45 UTC
The back and forward arrows within studentsms are not working. You can double click to add but this isn't intuitive. 
![screen shot 2013-10-18 at 15 43 15](https://f.cloud.github.com/assets/1598231/1361213/de360ff2-3803-11e3-944f-933d53e96fb8.png)

**Comment by oscott** [comment] 2014-01-10 14:25
this is a duplicate of #199

**Closed as completed by oscott** 2014-01-10 14:25 UTC
Labels: Duplicate
