### ISSUE TITLE
Via Tender: Profile Options

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#41] opened 2013-08-19 15:22 UTC
Assigned to [Help #33](http://et.tenderapp.com/discussions/help/33-profile-options). As reported in Tender:

<blockquote><p>Within learn.falmouth.ac.uk profile page there is a button to customise your profile which doesn't do anything. Think it's best to maybe remove this?</p></blockquote>

**Comment by themarkness** [comment] 2013-08-22 09:00
As detailed here in screenshot, it is a duplicate of 'turn editing on', but doesn't allow a user to do anything. Assigned to Aaron to advise.

![screen shot 2013-08-22 at 09 58 56](https://f.cloud.github.com/assets/1681436/1007464/2c7802ec-0b09-11e3-910c-cde8e649ce1f.png)

**Comment by damienh** [comment] 2013-10-03 12:52
I cant see this on new LearningSpace so im closing now

**Closed as completed by damienh** 2013-10-03 12:52 UTC
