### ISSUE TITLE
Moodletxt Styling 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#199] opened 2013-10-09 10:10 UTC
Moodletxt/StudentSMS is not displaying correctly. 

I'm on Chrome. 
![screen shot 2013-10-09 at 11 07 15](https://f.cloud.github.com/assets/1598231/1296582/ddd4649a-30ca-11e3-8ada-6e41c75d5f15.png)

http://learn-dev.falmouth.ac.uk/blocks/moodletxt/send.php?course=2&instance=3779

**Comment by Asampson** [comment] 2013-10-09 10:35
This is it in another theme.

![screen shot 2013-10-09 at 11 34 18](https://f.cloud.github.com/assets/1598231/1296693/7d0b0bba-30ce-11e3-8d2b-9373f8dca822.png)

**Comment by oscott** [comment] 2013-10-10 09:06
@Asampson @damienh @themarkness 

Looked at this with Aaron, Seeing as its a staff view that is pretty horrific by design. It'll either have to wait, or never be fixed. 

What we need to be doing is saying something like "it's ugly but it works, we hope to look into something better oneday" when we are showing staff how to use it. 

Can this get included in one to one, consultation, training, documentation, knowledge base, etc?

**Comment by Asampson** [comment] 2013-10-24 14:39
Buttons currently aren't working for this plug in either #235

**Comment by damienh** [comment] 2013-12-20 11:13
@aaronmarruk to look at buttons.

**Comment by oscott** [comment] 2014-01-10 14:04
The width issue is fixed in the next theme update. The button issue doesn't appear to be caused by the theme.

Can @damienh  or @Asampson please check to see if the module actually works in another theme? perhaps its a bug thats been fixed elsewhere?

**Comment by damienh** [comment] 2014-02-06 09:57
I am closing this as this plugin is looking to be made redundant.

**Closed as completed by damienh** 2014-02-06 09:57 UTC
